### ISSUE TITLE
Do you mind sharing the steps on how you add fine tuned model?

### ISSUE THREAD

**Issue by codenan42** [DigitLib/whisper-webui-vad#1]
I search through all your scripts and commits and i can't still find the way you added the fine tuned Serbian model.  All I see was you added this line "large-v2-sr" but how is it packaged together with whisper? I'm confuse. I have a lot of fine tune model i want to try that works decently on real time translation but would love to see if it works great on videos too.

**Comment by DigitLib** [comment]
@whizyre There are in README 
Update: Added Fine Tuned Serbian large-v2 Whisper model, named large-v2-sr
Repo: [whisper-for-low-vram-sr](https://github.com/DigitLib/whisper-for-low-vram-sr/whisper)
Need to fork this repo and add a link to model in [_init_.py](https://github.com/DigitLib/whisper-for-low-vram-sr/blob/main/whisper/__init__.py) 
Hope to find more elegant way to solve this but. 

Good luck!

**Comment by codenan42** [comment]
Hello thank you so much for your reply! Its a bit confusing but I'll try my best to make it work now that I understand how you add it. Thank you again!
